// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// my_trunc
double my_trunc(double x);
RcppExport SEXP _MPP_my_trunc(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(my_trunc(x));
    return rcpp_result_gen;
END_RCPP
}
// makeLowTriMat
arma::mat makeLowTriMat(const arma::mat& V, const arma::vec& Lvec);
RcppExport SEXP _MPP_makeLowTriMat(SEXP VSEXP, SEXP LvecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Lvec(LvecSEXP);
    rcpp_result_gen = Rcpp::wrap(makeLowTriMat(V, Lvec));
    return rcpp_result_gen;
END_RCPP
}
// LowTriVec
arma::vec LowTriVec(const arma::mat& V);
RcppExport SEXP _MPP_LowTriVec(SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(LowTriVec(V));
    return rcpp_result_gen;
END_RCPP
}
// Bdiag
arma::mat Bdiag(const arma::field<arma::mat>& M);
RcppExport SEXP _MPP_Bdiag(SEXP MSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type M(MSEXP);
    rcpp_result_gen = Rcpp::wrap(Bdiag(M));
    return rcpp_result_gen;
END_RCPP
}
// myinvCpp
arma::mat myinvCpp(const arma::mat& A);
RcppExport SEXP _MPP_myinvCpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(myinvCpp(A));
    return rcpp_result_gen;
END_RCPP
}
// myinvCpp2
arma::mat myinvCpp2(const arma::mat& A);
RcppExport SEXP _MPP_myinvCpp2(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(myinvCpp2(A));
    return rcpp_result_gen;
END_RCPP
}
// myCholCpp
arma::mat myCholCpp(arma::mat A);
RcppExport SEXP _MPP_myCholCpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(myCholCpp(A));
    return rcpp_result_gen;
END_RCPP
}
// myCholCpp2
arma::mat myCholCpp2(arma::mat A);
RcppExport SEXP _MPP_myCholCpp2(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(myCholCpp2(A));
    return rcpp_result_gen;
END_RCPP
}
// init_LME
List init_LME(arma::vec weights, arma::field<arma::vec> Y, arma::field<arma::mat> X, arma::field<arma::mat> Z, const int maxiter, const double eps);
RcppExport SEXP _MPP_init_LME(SEXP weightsSEXP, SEXP YSEXP, SEXP XSEXP, SEXP ZSEXP, SEXP maxiterSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::vec> >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::field<arma::mat> >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(init_LME(weights, Y, X, Z, maxiter, eps));
    return rcpp_result_gen;
END_RCPP
}
// init_LME2_one_marker
List init_LME2_one_marker(const arma::vec& weights, const arma::field<arma::vec>& W, const arma::field<arma::mat>& U, const arma::field<arma::mat>& Vdesign, const int maxiter, const double eps, const double ridge);
RcppExport SEXP _MPP_init_LME2_one_marker(SEXP weightsSEXP, SEXP WSEXP, SEXP USEXP, SEXP VdesignSEXP, SEXP maxiterSEXP, SEXP epsSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::vec>& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type U(USEXP);
    Rcpp::traits::input_parameter< const arma::field<arma::mat>& >::type Vdesign(VdesignSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< const double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(init_LME2_one_marker(weights, W, U, Vdesign, maxiter, eps, ridge));
    return rcpp_result_gen;
END_RCPP
}
// test_MPP_para_t_basic
List test_MPP_para_t_basic();
RcppExport SEXP _MPP_test_MPP_para_t_basic() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(test_MPP_para_t_basic());
    return rcpp_result_gen;
END_RCPP
}
// test_model
List test_model(const List& datalist, const List& paralist);
RcppExport SEXP _MPP_test_model(SEXP datalistSEXP, SEXP paralistSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type datalist(datalistSEXP);
    Rcpp::traits::input_parameter< const List& >::type paralist(paralistSEXP);
    rcpp_result_gen = Rcpp::wrap(test_model(datalist, paralist));
    return rcpp_result_gen;
END_RCPP
}
// test_MPP_MuZ_eval
List test_MPP_MuZ_eval(const List& datalist, const List& paralist, int i_R);
RcppExport SEXP _MPP_test_MPP_MuZ_eval(SEXP datalistSEXP, SEXP paralistSEXP, SEXP i_RSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const List& >::type datalist(datalistSEXP);
    Rcpp::traits::input_parameter< const List& >::type paralist(paralistSEXP);
    Rcpp::traits::input_parameter< int >::type i_R(i_RSEXP);
    rcpp_result_gen = Rcpp::wrap(test_MPP_MuZ_eval(datalist, paralist, i_R));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MPP_my_trunc", (DL_FUNC) &_MPP_my_trunc, 1},
    {"_MPP_makeLowTriMat", (DL_FUNC) &_MPP_makeLowTriMat, 2},
    {"_MPP_LowTriVec", (DL_FUNC) &_MPP_LowTriVec, 1},
    {"_MPP_Bdiag", (DL_FUNC) &_MPP_Bdiag, 1},
    {"_MPP_myinvCpp", (DL_FUNC) &_MPP_myinvCpp, 1},
    {"_MPP_myinvCpp2", (DL_FUNC) &_MPP_myinvCpp2, 1},
    {"_MPP_myCholCpp", (DL_FUNC) &_MPP_myCholCpp, 1},
    {"_MPP_myCholCpp2", (DL_FUNC) &_MPP_myCholCpp2, 1},
    {"_MPP_init_LME", (DL_FUNC) &_MPP_init_LME, 6},
    {"_MPP_init_LME2_one_marker", (DL_FUNC) &_MPP_init_LME2_one_marker, 7},
    {"_MPP_test_MPP_para_t_basic", (DL_FUNC) &_MPP_test_MPP_para_t_basic, 0},
    {"_MPP_test_model", (DL_FUNC) &_MPP_test_model, 2},
    {"_MPP_test_MPP_MuZ_eval", (DL_FUNC) &_MPP_test_MPP_MuZ_eval, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MPP(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
