# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

my_trunc <- function(x) {
    .Call(`_MPP_my_trunc`, x)
}

makeLowTriMat <- function(V, Lvec) {
    .Call(`_MPP_makeLowTriMat`, V, Lvec)
}

LowTriVec <- function(V) {
    .Call(`_MPP_LowTriVec`, V)
}

Bdiag <- function(M) {
    .Call(`_MPP_Bdiag`, M)
}

myinvCpp <- function(A) {
    .Call(`_MPP_myinvCpp`, A)
}

myinvCpp2 <- function(A) {
    .Call(`_MPP_myinvCpp2`, A)
}

myCholCpp <- function(A) {
    .Call(`_MPP_myCholCpp`, A)
}

myCholCpp2 <- function(A) {
    .Call(`_MPP_myCholCpp2`, A)
}

init_LME <- function(weights, Y, X, Z, maxiter = 100L, eps = 1e-4) {
    .Call(`_MPP_init_LME`, weights, Y, X, Z, maxiter, eps)
}

init_LME2_one_marker <- function(weights, W, U, Vdesign, maxiter = 100L, eps = 1e-4, ridge = 1e-8) {
    .Call(`_MPP_init_LME2_one_marker`, weights, W, U, Vdesign, maxiter, eps, ridge)
}

